version: '3.2'

services:
  form-processor:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=FILL_ME_IN
      - AWS_SECRET_ACCESS_KEY=FILL_ME_IN
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
